name: CI Pipeline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout repo
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # Cache NuGet packages
      # -----------------------------
      - name: Cache NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # -----------------------------
      # Install .NET SDK
      # -----------------------------
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # -----------------------------
      # Restore dependencies
      # -----------------------------
      - name: Restore
        run: dotnet restore SmartHome.sln

      # -----------------------------
      # Build (fail fast)
      # -----------------------------
      - name: Build
        run: dotnet build SmartHome.sln --configuration Release --no-restore

      # -----------------------------
      # Run unit tests with coverage
      # -----------------------------
      - name: Run Tests
        run:  dotnet test DeviceService.Tests/DeviceService.Tests.csproj --configuration Debug --no-build --verbosity normal


      # -----------------------------
      # Upload coverage report
      # -----------------------------
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: TestResults/coverage/

      # -----------------------------
      # Upload test results (trx)
      # -----------------------------
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"
